//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string Account_Confirm {
            get {
                return ResourceManager.GetString("Account_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa xin vui lòng liên hệ quản trị hệ thống để biết thêm chi tiết..
        /// </summary>
        public static string Account_Locked {
            get {
                return ResourceManager.GetString("Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngưng sử dụng.
        /// </summary>
        public static string Actived_False {
            get {
                return ResourceManager.GetString("Actived_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        public static string Actived_True {
            get {
                return ResourceManager.GetString("Actived_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới {0} thành công!.
        /// </summary>
        public static string Alert_Create_Success {
            get {
                return ResourceManager.GetString("Alert_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} thành công!.
        /// </summary>
        public static string Alert_Delete_Success {
            get {
                return ResourceManager.GetString("Alert_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} thành công!.
        /// </summary>
        public static string Alert_Edit_Success {
            get {
                return ResourceManager.GetString("Alert_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} cần xóa!.
        /// </summary>
        public static string Alert_NotExist_Delete {
            get {
                return ResourceManager.GetString("Alert_NotExist_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc.
        /// </summary>
        public static string Bac {
            get {
                return ResourceManager.GetString("Bac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc lương.
        /// </summary>
        public static string BacLuong {
            get {
                return ResourceManager.GetString("BacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bổ nhiệm cán bộ.
        /// </summary>
        public static string BoNhiem {
            get {
                return ResourceManager.GetString("BoNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Btn_Del {
            get {
                return ResourceManager.GetString("Btn_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc file excel.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục.
        /// </summary>
        public static string Btn_SaveAndContinue {
            get {
                return ResourceManager.GetString("Btn_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ.
        /// </summary>
        public static string CanBo {
            get {
                return ResourceManager.GetString("CanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại {0} này!.
        /// </summary>
        public static string Check_Exist {
            get {
                return ResourceManager.GetString("Check_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chổ ở hiện nay.
        /// </summary>
        public static string ChoOHienNay {
            get {
                return ResourceManager.GetString("ChoOHienNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string ChucVu {
            get {
                return ResourceManager.GetString("ChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        public static string ChuyenNganh {
            get {
                return ResourceManager.GetString("ChuyenNganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công tác.
        /// </summary>
        public static string CongTac {
            get {
                return ResourceManager.GetString("CongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở.
        /// </summary>
        public static string CoSo {
            get {
                return ResourceManager.GetString("CoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tạo.
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dân tộc.
        /// </summary>
        public static string DanToc {
            get {
                return ResourceManager.GetString("DanToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo bồi dưởng.
        /// </summary>
        public static string DaoTaoBoiDuong {
            get {
                return ResourceManager.GetString("DaoTaoBoiDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Tất cả --.
        /// </summary>
        public static string Dropdownlist_All {
            get {
                return ResourceManager.GetString("Dropdownlist_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Vui lòng chọn danh mục --.
        /// </summary>
        public static string Dropdownlist_Menu {
            get {
                return ResourceManager.GetString("Dropdownlist_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} này!.
        /// </summary>
        public static string Error_NotExist {
            get {
                return ResourceManager.GetString("Error_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string GioiTinh {
            get {
                return ResourceManager.GetString("GioiTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ đào tạo.
        /// </summary>
        public static string HeDaoTao {
            get {
                return ResourceManager.GetString("HeDaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ số.
        /// </summary>
        public static string HeSo {
            get {
                return ResourceManager.GetString("HeSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học Hàm.
        /// </summary>
        public static string HocHam {
            get {
                return ResourceManager.GetString("HocHam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ đệm.
        /// </summary>
        public static string HoDem {
            get {
                return ResourceManager.GetString("HoDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội viên.
        /// </summary>
        public static string HoiVien {
            get {
                return ResourceManager.GetString("HoiVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Href {
            get {
                return ResourceManager.GetString("Href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hưu trí.
        /// </summary>
        public static string HuuTri {
            get {
                return ResourceManager.GetString("HuuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen thưởng.
        /// </summary>
        public static string KhenThuong {
            get {
                return ResourceManager.GetString("KhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoán đến ngày.
        /// </summary>
        public static string KhoanDenNgay {
            get {
                return ResourceManager.GetString("KhoanDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoán từ ngày.
        /// </summary>
        public static string KhoanTuNgay {
            get {
                return ResourceManager.GetString("KhoanTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỷ luật.
        /// </summary>
        public static string KyLuat {
            get {
                return ResourceManager.GetString("KyLuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cuối cùng chỉnh sửa.
        /// </summary>
        public static string LastModifyDate {
            get {
                return ResourceManager.GetString("LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người cuối cùng chỉnh sửa.
        /// </summary>
        public static string LastModifyUser {
            get {
                return ResourceManager.GetString("LastModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        public static string Luong {
            get {
                return ResourceManager.GetString("Luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương khoán.
        /// </summary>
        public static string LuongKhoan {
            get {
                return ResourceManager.GetString("LuongKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bậc lương.
        /// </summary>
        public static string MaBacLuong {
            get {
                return ResourceManager.GetString("MaBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cán bộ.
        /// </summary>
        public static string MaCanBo {
            get {
                return ResourceManager.GetString("MaCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại ngạch.
        /// </summary>
        public static string MaLoai {
            get {
                return ResourceManager.GetString("MaLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ngạch lương.
        /// </summary>
        public static string MaNgachLuong {
            get {
                return ResourceManager.GetString("MaNgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string MaSoThue {
            get {
                return ResourceManager.GetString("MaSoThue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nền.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên rút rọn.
        /// </summary>
        public static string MenuCode {
            get {
                return ResourceManager.GetString("MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu cha.
        /// </summary>
        public static string MenuIdParent {
            get {
                return ResourceManager.GetString("MenuIdParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên menu.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn nhiệm cán bộ.
        /// </summary>
        public static string MienNhiem {
            get {
                return ResourceManager.GetString("MienNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm nâng bậc.
        /// </summary>
        public static string NamTangLuong {
            get {
                return ResourceManager.GetString("NamTangLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngạch lương.
        /// </summary>
        public static string NgachLuong {
            get {
                return ResourceManager.GetString("NgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp CCCD.
        /// </summary>
        public static string NgayCapCCCD {
            get {
                return ResourceManager.GetString("NgayCapCCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nâng bậc.
        /// </summary>
        public static string NgayNangBacLuong {
            get {
                return ResourceManager.GetString("NgayNangBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia công tác.
        /// </summary>
        public static string NgayThamGiaCongTac {
            get {
                return ResourceManager.GetString("NgayThamGiaCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào biên chế.
        /// </summary>
        public static string NgayVaoBienChe {
            get {
                return ResourceManager.GetString("NgayVaoBienChe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào đảng chính thức.
        /// </summary>
        public static string NgayVaoDangChinhThuc {
            get {
                return ResourceManager.GetString("NgayVaoDangChinhThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào đảng dự bị.
        /// </summary>
        public static string NgayvaoDangDuBi {
            get {
                return ResourceManager.GetString("NgayvaoDangDuBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân sự.
        /// </summary>
        public static string NhanSu {
            get {
                return ResourceManager.GetString("NhanSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi sinh.
        /// </summary>
        public static string NoiSinh {
            get {
                return ResourceManager.GetString("NoiSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string NumberIndex {
            get {
                return ResourceManager.GetString("NumberIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự hiển thị.
        /// </summary>
        public static string OrderIndex {
            get {
                return ResourceManager.GetString("OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân hệ.
        /// </summary>
        public static string PhanHe {
            get {
                return ResourceManager.GetString("PhanHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp.
        /// </summary>
        public static string PhuCap {
            get {
                return ResourceManager.GetString("PhuCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp chức vụ.
        /// </summary>
        public static string PhuCapChucVu {
            get {
                return ResourceManager.GetString("PhuCapChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp khu vực.
        /// </summary>
        public static string PhuCapKhuVuc {
            get {
                return ResourceManager.GetString("PhuCapKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp kiêm nhiệm.
        /// </summary>
        public static string PhuCapKiemNhiem {
            get {
                return ResourceManager.GetString("PhuCapKiemNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp vượt khung.
        /// </summary>
        public static string PhuCapVuotKhung {
            get {
                return ResourceManager.GetString("PhuCapVuotKhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In lý lịch.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dự án.
        /// </summary>
        public static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dự án.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan hệ gia đình.
        /// </summary>
        public static string QuanHeGiaDinh {
            get {
                return ResourceManager.GetString("QuanHeGiaDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình.
        /// </summary>
        public static string QuanLyQuaTrinh {
            get {
                return ResourceManager.GetString("QuanLyQuaTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ mật khẩu.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required_Dropdownlist {
            get {
                return ResourceManager.GetString("Required_Dropdownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quyền.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm quyền.
        /// </summary>
        public static string RolesCode {
            get {
                return ResourceManager.GetString("RolesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm quyền.
        /// </summary>
        public static string RolesName {
            get {
                return ResourceManager.GetString("RolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BHXH.
        /// </summary>
        public static string SoBHXH {
            get {
                return ResourceManager.GetString("SoBHXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BHYT.
        /// </summary>
        public static string SoBHYT {
            get {
                return ResourceManager.GetString("SoBHYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CCCD.
        /// </summary>
        public static string SoCCCD {
            get {
                return ResourceManager.GetString("SoCCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string SoDienThoai {
            get {
                return ResourceManager.GetString("SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bậc lương.
        /// </summary>
        public static string TenBacLuong {
            get {
                return ResourceManager.GetString("TenBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cơ sở.
        /// </summary>
        public static string TenCoSo {
            get {
                return ResourceManager.GetString("TenCoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngạch lương.
        /// </summary>
        public static string TenNgachLuong {
            get {
                return ResourceManager.GetString("TenNgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyên chuyển cán bộ.
        /// </summary>
        public static string ThuyenChuyenCanBo {
            get {
                return ResourceManager.GetString("ThuyenChuyenCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracker.
        /// </summary>
        public static string TimeTracker {
            get {
                return ResourceManager.GetString("TimeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string TinhTrang {
            get {
                return ResourceManager.GetString("TinhTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôn giáo.
        /// </summary>
        public static string TonGiao {
            get {
                return ResourceManager.GetString("TonGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ chính trị.
        /// </summary>
        public static string TrinhDoChinhTri {
            get {
                return ResourceManager.GetString("TrinhDoChinhTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ chuyên môn.
        /// </summary>
        public static string TrinhDoChuyenMon {
            get {
                return ResourceManager.GetString("TrinhDoChuyenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ học vấn.
        /// </summary>
        public static string TrinhDoHocVan {
            get {
                return ResourceManager.GetString("TrinhDoHocVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ ngoại ngữ.
        /// </summary>
        public static string TrinhDoNgoaiNgu {
            get {
                return ResourceManager.GetString("TrinhDoNgoaiNgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ tin học.
        /// </summary>
        public static string TrinhDoTinHoc {
            get {
                return ResourceManager.GetString("TrinhDoTinHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là dạng số lớn hơn 0!.
        /// </summary>
        public static string Validation_OrderIndex {
            get {
                return ResourceManager.GetString("Validation_OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem quá trình.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
