//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiNongDan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoiNongDan.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Dùng.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string Account_Confirm {
            get {
                return ResourceManager.GetString("Account_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa xin vui lòng liên hệ quản trị hệ thống để biết thêm chi tiết..
        /// </summary>
        public static string Account_Locked {
            get {
                return ResourceManager.GetString("Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng hoạt động.
        /// </summary>
        public static string Actived_False {
            get {
                return ResourceManager.GetString("Actived_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        public static string Actived_True {
            get {
                return ResourceManager.GetString("Actived_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới {0} thành công!.
        /// </summary>
        public static string Alert_Create_Success {
            get {
                return ResourceManager.GetString("Alert_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} thành công!.
        /// </summary>
        public static string Alert_Delete_Success {
            get {
                return ResourceManager.GetString("Alert_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} thành công!.
        /// </summary>
        public static string Alert_Edit_Success {
            get {
                return ResourceManager.GetString("Alert_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} cần xóa!.
        /// </summary>
        public static string Alert_NotExist_Delete {
            get {
                return ResourceManager.GetString("Alert_NotExist_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc.
        /// </summary>
        public static string Bac {
            get {
                return ResourceManager.GetString("Bac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc Lương.
        /// </summary>
        public static string BacLuong {
            get {
                return ResourceManager.GetString("BacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban chấp hành.
        /// </summary>
        public static string BanChapHanh {
            get {
                return ResourceManager.GetString("BanChapHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCH HNDTP.
        /// </summary>
        public static string BCHHNDTP {
            get {
                return ResourceManager.GetString("BCHHNDTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bồi Dưỡng.
        /// </summary>
        public static string BoiDuong {
            get {
                return ResourceManager.GetString("BoiDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bổ Nhiệm/Thuyên Chuyển Cán Bộ.
        /// </summary>
        public static string BoNhiem {
            get {
                return ResourceManager.GetString("BoNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Btn_Del {
            get {
                return ResourceManager.GetString("Btn_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc file excel.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục.
        /// </summary>
        public static string Btn_SaveAndContinue {
            get {
                return ResourceManager.GetString("Btn_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán Bộ.
        /// </summary>
        public static string CanBo {
            get {
                return ResourceManager.GetString("CanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ HND H, Q, X, P.
        /// </summary>
        public static string CanBoHNDQHXP {
            get {
                return ResourceManager.GetString("CanBoHNDQHXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ HND TP qua các thời kỳ.
        /// </summary>
        public static string CanBoHNDQuaCacThoiKy {
            get {
                return ResourceManager.GetString("CanBoHNDQuaCacThoiKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ Hội Nông dân TP.
        /// </summary>
        public static string CanBoHNDTP {
            get {
                return ResourceManager.GetString("CanBoHNDTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tình trạng cán bộ.
        /// </summary>
        public static string CapNhatTinhTrangCanBo {
            get {
                return ResourceManager.GetString("CapNhatTinhTrangCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại {0} này!.
        /// </summary>
        public static string Check_Exist {
            get {
                return ResourceManager.GetString("Check_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chổ ở hiện nay.
        /// </summary>
        public static string ChoOHienNay {
            get {
                return ResourceManager.GetString("ChoOHienNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string ChucVu {
            get {
                return ResourceManager.GetString("ChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        public static string ChuyenNganh {
            get {
                return ResourceManager.GetString("ChuyenNganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công Tác.
        /// </summary>
        public static string CongTac {
            get {
                return ResourceManager.GetString("CongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở.
        /// </summary>
        public static string CoSo {
            get {
                return ResourceManager.GetString("CoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở đào tạo.
        /// </summary>
        public static string CoSoDaoTao {
            get {
                return ResourceManager.GetString("CoSoDaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tạo.
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh hiệu khen thưởng.
        /// </summary>
        public static string DanhHieuKhenThuong {
            get {
                return ResourceManager.GetString("DanhHieuKhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dân Tộc.
        /// </summary>
        public static string DanToc {
            get {
                return ResourceManager.GetString("DanToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào Tạo.
        /// </summary>
        public static string DaoTao {
            get {
                return ResourceManager.GetString("DaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo bồi dưởng.
        /// </summary>
        public static string DaoTaoBoiDuong {
            get {
                return ResourceManager.GetString("DaoTaoBoiDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn từ danh sách.
        /// </summary>
        public static string DataValidationError {
            get {
                return ResourceManager.GetString("DataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string DenNgay {
            get {
                return ResourceManager.GetString("DenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban, Văn Phòng, Trung Tâm.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban, Văn Phòng, Trung Tâm.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa bàn hoạt động.
        /// </summary>
        public static string DiaBanHoatDong {
            get {
                return ResourceManager.GetString("DiaBanHoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diện tích.
        /// </summary>
        public static string DienTich {
            get {
                return ResourceManager.GetString("DienTich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Tất cả --.
        /// </summary>
        public static string Dropdownlist_All {
            get {
                return ResourceManager.GetString("Dropdownlist_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Vui lòng chọn danh mục --.
        /// </summary>
        public static string Dropdownlist_Menu {
            get {
                return ResourceManager.GetString("Dropdownlist_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt Hội Viên mới.
        /// </summary>
        public static string DuyetHoiVienMoi {
            get {
                return ResourceManager.GetString("DuyetHoiVienMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0} này!.
        /// </summary>
        public static string Error_NotExist {
            get {
                return ResourceManager.GetString("Error_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách {0}.
        /// </summary>
        public static string Export_ExcelHeader {
            get {
                return ResourceManager.GetString("Export_ExcelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (*).
        /// </summary>
        public static string Export_ExcelRequired {
            get {
                return ResourceManager.GetString("Export_ExcelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý: Chỉ chỉnh sửa những ô màu vàng.
        /// </summary>
        public static string Export_ExcelWarning1 {
            get {
                return ResourceManager.GetString("Export_ExcelWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập những cột có chứa dấu (*).
        /// </summary>
        public static string Export_ExcelWarning2 {
            get {
                return ResourceManager.GetString("Export_ExcelWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đính kèm.
        /// </summary>
        public static string FileDinhKem {
            get {
                return ResourceManager.GetString("FileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia đình thuộc diện.
        /// </summary>
        public static string GiaDinhThuocDien {
            get {
                return ResourceManager.GetString("GiaDinhThuocDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string GioiTinh {
            get {
                return ResourceManager.GetString("GioiTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ đào tạo.
        /// </summary>
        public static string HeDaoTao {
            get {
                return ResourceManager.GetString("HeDaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ số.
        /// </summary>
        public static string HeSo {
            get {
                return ResourceManager.GetString("HeSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ số chức vụ.
        /// </summary>
        public static string HeSoChucVu {
            get {
                return ResourceManager.GetString("HeSoChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức khen thưởng.
        /// </summary>
        public static string HinhThucKhenThuong {
            get {
                return ResourceManager.GetString("HinhThucKhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức kỷ luật.
        /// </summary>
        public static string HinhThucKyLuat {
            get {
                return ResourceManager.GetString("HinhThucKyLuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học Hàm.
        /// </summary>
        public static string HocHam {
            get {
                return ResourceManager.GetString("HocHam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học vị.
        /// </summary>
        public static string HocVi {
            get {
                return ResourceManager.GetString("HocVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ đệm.
        /// </summary>
        public static string HoDem {
            get {
                return ResourceManager.GetString("HoDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội Viên nông dân.
        /// </summary>
        public static string HoiVien {
            get {
                return ResourceManager.GetString("HoiVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội viên vay vốn.
        /// </summary>
        public static string HoiVienVayVon {
            get {
                return ResourceManager.GetString("HoiVienVayVon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hộ khẩu thường trú.
        /// </summary>
        public static string HoKhauThuongTru {
            get {
                return ResourceManager.GetString("HoKhauThuongTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Href {
            get {
                return ResourceManager.GetString("Href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hưu Trí.
        /// </summary>
        public static string HuuTri {
            get {
                return ResourceManager.GetString("HuuTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Hình thức Được Khen Tặng.
        /// </summary>
        public static string HVKhenThuong {
            get {
                return ResourceManager.GetString("HVKhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import excel.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dữ liệu thành công!.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen thưởng.
        /// </summary>
        public static string KhenThuong {
            get {
                return ResourceManager.GetString("KhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoán đến ngày.
        /// </summary>
        public static string KhoanDenNgay {
            get {
                return ResourceManager.GetString("KhoanDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoán từ ngày.
        /// </summary>
        public static string KhoanTuNgay {
            get {
                return ResourceManager.GetString("KhoanTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỷ Luật.
        /// </summary>
        public static string KyLuat {
            get {
                return ResourceManager.GetString("KyLuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lãi suất vay/Tháng.
        /// </summary>
        public static string LaiSuatVay {
            get {
                return ResourceManager.GetString("LaiSuatVay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cuối cùng chỉnh sửa.
        /// </summary>
        public static string LastModifyDate {
            get {
                return ResourceManager.GetString("LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người cuối cùng chỉnh sửa.
        /// </summary>
        public static string LastModifyUser {
            get {
                return ResourceManager.GetString("LastModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string Loai {
            get {
                return ResourceManager.GetString("Loai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình, dịch vụ sản xuất, chăn nuôi.
        /// </summary>
        public static string Loai_DV_SX_ChN {
            get {
                return ResourceManager.GetString("Loai_DV_SX_ChN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hội viên.
        /// </summary>
        public static string LoaiHoiVien {
            get {
                return ResourceManager.GetString("LoaiHoiVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại quan hệ.
        /// </summary>
        public static string LoaiQuanhe {
            get {
                return ResourceManager.GetString("LoaiQuanhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luận án tốt nghiệp.
        /// </summary>
        public static string LuanAnTN {
            get {
                return ResourceManager.GetString("LuanAnTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        public static string Luong {
            get {
                return ResourceManager.GetString("Luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương khoán.
        /// </summary>
        public static string LuongKhoan {
            get {
                return ResourceManager.GetString("LuongKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do.
        /// </summary>
        public static string LyDo {
            get {
                return ResourceManager.GetString("LyDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string Ma {
            get {
                return ResourceManager.GetString("Ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bậc lương.
        /// </summary>
        public static string MaBacLuong {
            get {
                return ResourceManager.GetString("MaBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cán bộ.
        /// </summary>
        public static string MaCanBo {
            get {
                return ResourceManager.GetString("MaCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        public static string MaChuyenNganh {
            get {
                return ResourceManager.GetString("MaChuyenNganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh.
        /// </summary>
        public static string MaDinhDanh {
            get {
                return ResourceManager.GetString("MaDinhDanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức đào tạo.
        /// </summary>
        public static string MaHinhThucDaoTao {
            get {
                return ResourceManager.GetString("MaHinhThucDaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ Hội viên.
        /// </summary>
        public static string MaHoiVien {
            get {
                return ResourceManager.GetString("MaHoiVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hội viên.
        /// </summary>
        public static string MaHV {
            get {
                return ResourceManager.GetString("MaHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại ngạch.
        /// </summary>
        public static string MaLoai {
            get {
                return ResourceManager.GetString("MaLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại bằng cấp.
        /// </summary>
        public static string MaLoaiBangCap {
            get {
                return ResourceManager.GetString("MaLoaiBangCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ngạch lương.
        /// </summary>
        public static string MaNgachLuong {
            get {
                return ResourceManager.GetString("MaNgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string MaSoThue {
            get {
                return ResourceManager.GetString("MaSoThue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ Liệu Nền.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên rút rọn.
        /// </summary>
        public static string MenuCode {
            get {
                return ResourceManager.GetString("MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu cha.
        /// </summary>
        public static string MenuIdParent {
            get {
                return ResourceManager.GetString("MenuIdParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên menu.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn Nhiệm Cán Bộ.
        /// </summary>
        public static string MienNhiem {
            get {
                return ResourceManager.GetString("MienNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm nâng bậc.
        /// </summary>
        public static string NamTangLuong {
            get {
                return ResourceManager.GetString("NamTangLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm vay.
        /// </summary>
        public static string NamVayVon {
            get {
                return ResourceManager.GetString("NamVayVon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngạch Lương.
        /// </summary>
        public static string NgachLuong {
            get {
                return ResourceManager.GetString("NgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string NgayBatDau {
            get {
                return ResourceManager.GetString("NgayBatDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp CCCD.
        /// </summary>
        public static string NgayCapCCCD {
            get {
                return ResourceManager.GetString("NgayCapCCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        public static string NgayKetThuc {
            get {
                return ResourceManager.GetString("NgayKetThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký.
        /// </summary>
        public static string NgayKy {
            get {
                return ResourceManager.GetString("NgayKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nâng bậc.
        /// </summary>
        public static string NgayNangBacLuong {
            get {
                return ResourceManager.GetString("NgayNangBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Quyết Định.
        /// </summary>
        public static string NgayQuyetDinh {
            get {
                return ResourceManager.GetString("NgayQuyetDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày rời đi.
        /// </summary>
        public static string NgayRoiDi {
            get {
                return ResourceManager.GetString("NgayRoiDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia cấp ủy đảng.
        /// </summary>
        public static string NgayThamGiaCapUyDang {
            get {
                return ResourceManager.GetString("NgayThamGiaCapUyDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia công tác.
        /// </summary>
        public static string NgayThamGiaCongTac {
            get {
                return ResourceManager.GetString("NgayThamGiaCongTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tham gia HĐND.
        /// </summary>
        public static string NgayThamGiaHDND {
            get {
                return ResourceManager.GetString("NgayThamGiaHDND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thành lập.
        /// </summary>
        public static string NgayThanhLap {
            get {
                return ResourceManager.GetString("NgayThanhLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tốt nghiệp.
        /// </summary>
        public static string NgayTotNghiep {
            get {
                return ResourceManager.GetString("NgayTotNghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày trả nợ CC.
        /// </summary>
        public static string NgayTraNoCuoiCung {
            get {
                return ResourceManager.GetString("NgayTraNoCuoiCung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào.
        /// </summary>
        public static string NgayVao {
            get {
                return ResourceManager.GetString("NgayVao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào biên chế.
        /// </summary>
        public static string NgayVaoBienChe {
            get {
                return ResourceManager.GetString("NgayVaoBienChe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào đảng chính thức.
        /// </summary>
        public static string NgayVaoDangChinhThuc {
            get {
                return ResourceManager.GetString("NgayVaoDangChinhThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào đảng dự bị.
        /// </summary>
        public static string NgayvaoDangDuBi {
            get {
                return ResourceManager.GetString("NgayvaoDangDuBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm vào hội.
        /// </summary>
        public static string NgayVaoHoi {
            get {
                return ResourceManager.GetString("NgayVaoHoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        public static string NgheNghiep {
            get {
                return ResourceManager.GetString("NgheNghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp hiện nay.
        /// </summary>
        public static string NgheNghiepHienNay {
            get {
                return ResourceManager.GetString("NgheNghiepHienNay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string NgonNgu {
            get {
                return ResourceManager.GetString("NgonNgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người ký.
        /// </summary>
        public static string NguoiKy {
            get {
                return ResourceManager.GetString("NguoiKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Sự.
        /// </summary>
        public static string NhanSu {
            get {
                return ResourceManager.GetString("NhanSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi bồi dưỡng.
        /// </summary>
        public static string NoiBoiDuong {
            get {
                return ResourceManager.GetString("NoiBoiDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string NoiDung {
            get {
                return ResourceManager.GetString("NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung vay.
        /// </summary>
        public static string NoiDungVay {
            get {
                return ResourceManager.GetString("NoiDungVay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm việc.
        /// </summary>
        public static string NoiLamViec {
            get {
                return ResourceManager.GetString("NoiLamViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm việc.
        /// </summary>
        public static string NoiLamVien {
            get {
                return ResourceManager.GetString("NoiLamVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi sinh.
        /// </summary>
        public static string NoiSinh {
            get {
                return ResourceManager.GetString("NoiSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string NumberIndex {
            get {
                return ResourceManager.GetString("NumberIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự hiển thị.
        /// </summary>
        public static string OrderIndex {
            get {
                return ResourceManager.GetString("OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân Quyền.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân hệ.
        /// </summary>
        public static string PhanHe {
            get {
                return ResourceManager.GetString("PhanHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ Cấp.
        /// </summary>
        public static string PhuCap {
            get {
                return ResourceManager.GetString("PhuCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp chức vụ.
        /// </summary>
        public static string PhuCapChucVu {
            get {
                return ResourceManager.GetString("PhuCapChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp khu vực.
        /// </summary>
        public static string PhuCapKhuVuc {
            get {
                return ResourceManager.GetString("PhuCapKhuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp kiêm nhiệm.
        /// </summary>
        public static string PhuCapKiemNhiem {
            get {
                return ResourceManager.GetString("PhuCapKiemNhiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp vượt khung.
        /// </summary>
        public static string PhuCapVuotKhung {
            get {
                return ResourceManager.GetString("PhuCapVuotKhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string PhuongXa {
            get {
                return ResourceManager.GetString("PhuongXa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In lý lịch.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cán bộ.
        /// </summary>
        public static string ProfileCanBo {
            get {
                return ResourceManager.GetString("ProfileCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dự án.
        /// </summary>
        public static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dự án.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan Hệ Gia Đình.
        /// </summary>
        public static string QHGiaDinh {
            get {
                return ResourceManager.GetString("QHGiaDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Cán Bộ Hội ND.
        /// </summary>
        public static string QLCanBoHoiND {
            get {
                return ResourceManager.GetString("QLCanBoHoiND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan Hệ Gia Đình.
        /// </summary>
        public static string QuanHeGiaDinh {
            get {
                return ResourceManager.GetString("QuanHeGiaDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string QuanHuyen {
            get {
                return ResourceManager.GetString("QuanHuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán Bội Hội ND Quá trình.
        /// </summary>
        public static string QuanLyQuaTrinh {
            get {
                return ResourceManager.GetString("QuanLyQuaTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào Tạo.
        /// </summary>
        public static string QuaTrinhDaoTao {
            get {
                return ResourceManager.GetString("QuaTrinhDaoTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen Thưởng.
        /// </summary>
        public static string QuaTrinhKhenThuong {
            get {
                return ResourceManager.GetString("QuaTrinhKhenThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string QuocGia {
            get {
                return ResourceManager.GetString("QuocGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ mật khẩu.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required_Dropdownlist {
            get {
                return ResourceManager.GetString("Required_Dropdownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm Quyền.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm quyền.
        /// </summary>
        public static string RolesCode {
            get {
                return ResourceManager.GetString("RolesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm quyền.
        /// </summary>
        public static string RolesName {
            get {
                return ResourceManager.GetString("RolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BHXH.
        /// </summary>
        public static string SoBHXH {
            get {
                return ResourceManager.GetString("SoBHXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BHYT.
        /// </summary>
        public static string SoBHYT {
            get {
                return ResourceManager.GetString("SoBHYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CCCD.
        /// </summary>
        public static string SoCCCD {
            get {
                return ResourceManager.GetString("SoCCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string SoDienThoai {
            get {
                return ResourceManager.GetString("SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string SoLuong {
            get {
                return ResourceManager.GetString("SoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hội viên.
        /// </summary>
        public static string SoLuongHoiVien {
            get {
                return ResourceManager.GetString("SoLuongHoiVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số quyết định.
        /// </summary>
        public static string SoQuyetDinh {
            get {
                return ResourceManager.GetString("SoQuyetDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tháng quá hạn.
        /// </summary>
        public static string SoThangQuaHan {
            get {
                return ResourceManager.GetString("SoThangQuaHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền vay.
        /// </summary>
        public static string SoTienVay {
            get {
                return ResourceManager.GetString("SoTienVay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bậc lương.
        /// </summary>
        public static string TenBacLuong {
            get {
                return ResourceManager.GetString("TenBacLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức vụ.
        /// </summary>
        public static string TenChucVu {
            get {
                return ResourceManager.GetString("TenChucVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Cơ Sở.
        /// </summary>
        public static string TenCoSo {
            get {
                return ResourceManager.GetString("TenCoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string TenDiaBanHoatDong {
            get {
                return ResourceManager.GetString("TenDiaBanHoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hội viên.
        /// </summary>
        public static string TenHV {
            get {
                return ResourceManager.GetString("TenHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngạch lương.
        /// </summary>
        public static string TenNgachLuong {
            get {
                return ResourceManager.GetString("TenNgachLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham gia câu lạc bộ, đội nhóm, mô hình, hợp tác xã, tổ hợp tác.
        /// </summary>
        public static string ThamGia_CLB_DN_MH_HTX_THT {
            get {
                return ResourceManager.GetString("ThamGia_CLB_DN_MH_HTX_THT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tham gia sinh hoạt  đoàn thể chính trị, Hội đoàn nào khác.
        /// </summary>
        public static string ThamGia_SH_DoanThe_HoiDoanKhac {
            get {
                return ResourceManager.GetString("ThamGia_SH_DoanThe_HoiDoanKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham gia tổ hội ngành nghề, chi hội ngành nghề.
        /// </summary>
        public static string ThamGia_THNN_CHNN {
            get {
                return ResourceManager.GetString("ThamGia_THNN_CHNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạng cho vay.
        /// </summary>
        public static string ThoiHangChoVay {
            get {
                return ResourceManager.GetString("ThoiHangChoVay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuyên Chuyển Cán Bộ.
        /// </summary>
        public static string ThuyenChuyenCanBo {
            get {
                return ResourceManager.GetString("ThuyenChuyenCanBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracker.
        /// </summary>
        public static string TimeTracker {
            get {
                return ResourceManager.GetString("TimeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố/Tỉnh.
        /// </summary>
        public static string TinhThanhPho {
            get {
                return ResourceManager.GetString("TinhThanhPho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string TinhTrang {
            get {
                return ResourceManager.GetString("TinhTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôn Giáo.
        /// </summary>
        public static string TonGiao {
            get {
                return ResourceManager.GetString("TonGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả xong.
        /// </summary>
        public static string TraXong {
            get {
                return ResourceManager.GetString("TraXong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Độ Chính Trị.
        /// </summary>
        public static string TrinhDoChinhTri {
            get {
                return ResourceManager.GetString("TrinhDoChinhTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Độ Chuyên Môn.
        /// </summary>
        public static string TrinhDoChuyenMon {
            get {
                return ResourceManager.GetString("TrinhDoChuyenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Độ Học Vấn.
        /// </summary>
        public static string TrinhDoHocVan {
            get {
                return ResourceManager.GetString("TrinhDoHocVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Độ Ngoại Ngữ.
        /// </summary>
        public static string TrinhDoNgoaiNgu {
            get {
                return ResourceManager.GetString("TrinhDoNgoaiNgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Độ Tin Học.
        /// </summary>
        public static string TrinhDoTinHoc {
            get {
                return ResourceManager.GetString("TrinhDoTinHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string TuNgay {
            get {
                return ResourceManager.GetString("TuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò.
        /// </summary>
        public static string VaiTro {
            get {
                return ResourceManager.GetString("VaiTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu file excel không phù hợp với chức năng &quot;{0}&quot;!.
        /// </summary>
        public static string Validation_ImportCheckController {
            get {
                return ResourceManager.GetString("Validation_ImportCheckController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một file excel!.
        /// </summary>
        public static string Validation_ImportExcelFile {
            get {
                return ResourceManager.GetString("Validation_ImportExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: &quot;{1}&quot; không tồn tại trong &quot;{2}&quot;!.
        /// </summary>
        public static string Validation_ImportExcelIdNotExist {
            get {
                return ResourceManager.GetString("Validation_ImportExcelIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ở dòng số {1}!.
        /// </summary>
        public static string Validation_ImportRequired {
            get {
                return ResourceManager.GetString("Validation_ImportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là dạng số lớn hơn 0!.
        /// </summary>
        public static string Validation_OrderIndex {
            get {
                return ResourceManager.GetString("Validation_OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem quá trình.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ đến tuổi nghỉ hưu.
        /// </summary>
        public static string XetNghiHuu {
            get {
                return ResourceManager.GetString("XetNghiHuu", resourceCulture);
            }
        }
    }
}
